//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MagicItem
    {
        public short MagicItemID { get; set; }
        public string MagicItemName { get; set; }
        public string Description { get; set; }
        public short CategoryID { get; set; }
        public short RarityID { get; set; }
        public short Price { get; set; }
        public short StatusID { get; set; }
        public short MakerID { get; set; }
        public string MagicItemImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Maker Maker { get; set; }
        public virtual Rarity Rarity { get; set; }
        public virtual Status Status { get; set; }
    }
}
